"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "What is MentoPanda?",
    answer:
      "MentoPanda is a platform that helps you build communication skills through realistic roleplay with AI characters. You can use pre-built scenarios or create your own tailored to your needs.",
  },
  {
    question: "How can I get started with MentoPanda?",
    answer:
      "Just sign up for a free account—no credit card required. You'll receive 75 credits to explore the platform, and you can upgrade to a subscription or purchase extra credits anytime.",
  },
  {
    question: "Can I get additional credits?",
    answer:
      "Yes! You can buy credit packs at any time, or switch to a subscription plan for recurring credits and additional features.",
  },
  {
    question: "Do the unused credits in subscription tiers roll over?",
    answer:
      "No, the unused credits in subscription tiers do not roll over. However, the additional credits you buy will roll over with an expiration period of 1 year.",
  },
  {
    question: "How accurate are the assessments?",
    answer:
      "Assessments are generated by AI (currently using OpenAI’s GPT-4o model) based on your conversation performance. While highly accurate, occasional transcription errors may affect results. You can also add your own scoring prompts to fine-tune lessons you create.",
  },
  {
    question: "Can I cancel my subscription?",
    answer:
      "Yes, you can cancel anytime from the Settings section. You’ll retain access to your plan and remaining credits until the end of your billing cycle.",
  },
  {
    question: "Are the lessons and characters I create shared with others?",
    answer:
      "No. Your custom lessons and characters are private by default. If you invite teammates to a project, they’ll have access to those resources. On Pro and higher tiers, you can manage multiple private projects with different teams.",
  },
  {
    question: "Can I invite my team to use MentoPanda?",
    answer:
      "Yes! Team features are available starting with the Pro tier. After upgrading, you can invite colleagues, assign roles (Admin, Manager, Member), and collaborate on training projects together.",
  },
];


export function FaqSection() {
  return (
    <section className="py-16 px-4 sm:px-6 lg:px-8">
      <div className="container mx-auto">
        <div className="text-center mb-16">
          <div className="text-brand font-medium mb-4">FAQ</div>
          <h2 className="text-4xl font-bold mb-16">
            Frequently asked questions
          </h2>
        </div>

        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent>{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
