"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "What is MentoPanda?",
    answer:
      "MentoPanda is a platform that helps you practice your communication skills with AI characters. You can use prebuilt scenarios or create your own.",
  },
  {
    question: "How can I get started with MentoPanda?",
    answer:
      "Getting started is easy! Sign up for a free account, and bring your own API Key from OpenAI. Or alternatively use our Pro account (coming soon) which includes all OpenAI fees and more.",
  },
  {
    question: "Is my OpenAI API Key stored on MentoPanda?",
    answer:
      "No, your OpenAI API Key is not stored on MentoPanda. It is stored in your browser's local storage. We do not have access to it and cannot see it.",
  },
  {
    question: "How accurate are my assessments?",
    answer:
      "The assessments are generated by the AI models (OpenAI). They are based on the conversation between the AI character and the user. Sometimes the transcriptions are not 100% accurate, which may affect the assessment. You can also add your own prompts to the assessments for your own lessons and improve the accuracy.",
  },
  {
    question:
      "When I create new lessons and characters, are they available for other users?",
    answer:
      "No, when you create a new lesson or character, it is private to you. If you invited your colleagues, they will also have access to it.",
  },
  {
    question: "Can I invite my team to use MentoPanda?",
    answer:
      "Yes of course! After you sign up, go to the team section and invite your team members from there. They will have access to the same lessons and characters as you. You can also setup what level of access they can have. Admins will have the same level of access as you are, managers will be able to create lessons and characters and members will only be able enroll in lessons and practice them.",
  },
];

export function FaqSection() {
  return (
    <section className="py-16 px-4 sm:px-6 lg:px-8">
      <div className="container mx-auto">
        <div className="text-center mb-16">
          <div className="text-brand font-medium mb-4">FAQ</div>
          <h2 className="text-4xl font-bold mb-16">
            Frequently asked questions
          </h2>
        </div>

        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent>{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
